# Generated by Django 5.2.1 on 2025-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="benutzer",
            name="erst_anmeldung",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="benutzer",
            name="nachname",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="benutzer",
            name="vorname",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
