# Generated by Django 5.2.1 on 2025-05-24 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kalendereintrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("ist_beendet", models.BooleanField(default=False)),
                ("beendet_am", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Kalendereintrag",
                "verbose_name_plural": "Kalendereinträge",
                "ordering": ["datum"],
            },
        ),
        migrations.CreateModel(
            name="Putzplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("erstellungsdatum", models.DateTimeField(auto_now_add=True)),
                ("ist_aktiv", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Putzplan",
                "verbose_name_plural": "Putzpläne",
            },
        ),
        migrations.CreateModel(
            name="Raum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bezeichnung", models.CharField(max_length=50)),
                ("beschreibung", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Raum",
                "verbose_name_plural": "Räume",
            },
        ),
        migrations.CreateModel(
            name="WG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("adresse", models.TextField()),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "WG",
                "verbose_name_plural": "WGs",
            },
        ),
        migrations.CreateModel(
            name="AufgabenStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ist_erledigt", models.BooleanField(default=False)),
                ("erledigt_am", models.DateTimeField(blank=True, null=True)),
                (
                    "kalendereintrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reinigung.kalendereintrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aufgaben Status",
                "verbose_name_plural": "Aufgaben Status",
            },
        ),
        migrations.CreateModel(
            name="MitbewohnerProfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beigetreten_am", models.DateTimeField(auto_now_add=True)),
                ("ist_aktiv", models.BooleanField(default=True)),
                (
                    "benutzer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitbewohner_profil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitbewohner",
                        to="reinigung.wg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitbewohner Profil",
                "verbose_name_plural": "Mitbewohner Profile",
                "unique_together": {("benutzer", "wg")},
            },
        ),
        migrations.AddField(
            model_name="kalendereintrag",
            name="mitbewohner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="putztermine",
                to="reinigung.mitbewohnerprofil",
            ),
        ),
        migrations.AddField(
            model_name="kalendereintrag",
            name="putzplan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eintraege",
                to="reinigung.putzplan",
            ),
        ),
        migrations.CreateModel(
            name="Reinigungsaufgabe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bezeichnung", models.CharField(max_length=100)),
                ("beschreibung", models.TextField(blank=True)),
                (
                    "haeufigkeit",
                    models.IntegerField(
                        default=1,
                        help_text="Wie oft pro Woche (Standard: 1 = wöchentlich)",
                    ),
                ),
                (
                    "schaetzzeit_minuten",
                    models.IntegerField(
                        default=30, help_text="Geschätzte Zeit in Minuten"
                    ),
                ),
                (
                    "raum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aufgaben",
                        to="reinigung.raum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reinigungsaufgabe",
                "verbose_name_plural": "Reinigungsaufgaben",
            },
        ),
        migrations.AddField(
            model_name="kalendereintrag",
            name="aufgaben",
            field=models.ManyToManyField(
                through="reinigung.AufgabenStatus", to="reinigung.reinigungsaufgabe"
            ),
        ),
        migrations.AddField(
            model_name="aufgabenstatus",
            name="aufgabe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reinigung.reinigungsaufgabe",
            ),
        ),
        migrations.AddField(
            model_name="raum",
            name="wg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raeume",
                to="reinigung.wg",
            ),
        ),
        migrations.AddField(
            model_name="putzplan",
            name="wg",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="putzplan",
                to="reinigung.wg",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kalendereintrag",
            unique_together={("putzplan", "datum")},
        ),
        migrations.AlterUniqueTogether(
            name="aufgabenstatus",
            unique_together={("kalendereintrag", "aufgabe")},
        ),
        migrations.AlterUniqueTogether(
            name="raum",
            unique_together={("wg", "bezeichnung")},
        ),
    ]
